Features closed for now

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,18 +20,18 @@ jobs:
           CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
-          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
+          JB_PUA_TOKEN: ${{ secrets.JB_PUA_TOKEN }}
         run: |
           test -n "$CERTIFICATE_CHAIN" || { echo "CERTIFICATE_CHAIN is missing"; exit 1; }
           test -n "$PRIVATE_KEY" || { echo "PRIVATE_KEY is missing"; exit 1; }
           test -n "$PRIVATE_KEY_PASSWORD" || { echo "PRIVATE_KEY_PASSWORD is missing"; exit 1; }
-          test -n "$PUBLISH_TOKEN" || { echo "PUBLISH_TOKEN is missing"; exit 1; }
+          test -n "$JB_PUA_TOKEN" || { echo "JB_PUA_TOKEN is missing"; exit 1; }
       - name: Test, sign, and publish
         env:
           CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
-          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
+          JB_PUA_TOKEN: ${{ secrets.JB_PUA_TOKEN }}
         run: ./gradlew test verifyPluginProjectConfiguration signPlugin publishPlugin
       - uses: softprops/action-gh-release@v2
         with:
